spring.application.name=CourseWork

spring:
  application:
    name:user-service

  datasource:
    url:jdbc:postgresql://localhost5432/user-service
    username:postgresql
    password:postgresql
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
